// The eight projects, in the order the work index shows them ("sorted by how much they prove").
// Categories give the work-index counts: AI systems 3 · Full-stack 3 · Research 2 · Mobile 1 · Experiments 1.
// `short` and `tagline` are the guarantee as the work index and the phone rows word it (from the artboards).
// Image icons name a file in src/assets/images (see lib/images.ts).
import type { Project } from './types';

export const projects: Project[] = [
  {
    slug: 'glassbox',
    name: 'GlassBox',
    guarantee: 'Every answer is cited or refused; every decision is hash-chained per tenant.',
    short: 'Every answer cited or refused; every decision hash-chained.',
    tagline: 'Every answer cited or refused',
    summary: 'Auditable wealth-advisory AI.',
    status: 'live',
    categories: ['ai-systems', 'full-stack'],
    stack: ['FastAPI', 'Next.js 16', 'Postgres', 'scikit-learn'],
    meta: 'FastAPI · Next.js · Postgres · 2026',
    year: '2026',
    icon: { glyph: 'box', gradient: 'linear-gradient(150deg, #2F6BFF 0%, #1E3A8A 60%, #0B1F4D 100%)' },
    href: '/work/glassbox',
    links: {
      caseStudy: '/work/glassbox',
      demo: 'https://glassbox.15-252-203-137.sslip.io',
      code: 'https://github.com/yash-vks-chauhan/Glassbox',
      video: '[90-second demo video]',
    },
    featured: true,
    sources: ['glassbox-eval-v4', 'glassbox-ci', 'glassbox-deploy'],
  },
  {
    slug: 'pulse',
    name: 'Pulse',
    guarantee: 'The LLM proposes a validated DSL. It never writes SQL, touches the database or sees PII.',
    short: 'The LLM proposes a validated DSL; never SQL, never PII.',
    tagline: 'LLM proposes a validated DSL',
    summary: 'AI-native campaign CRM.',
    status: 'live',
    categories: ['ai-systems', 'full-stack'],
    stack: ['NestJS', 'BullMQ', 'Prisma'],
    year: '2026',
    icon: { glyph: 'activity', gradient: 'linear-gradient(145deg, #8E8BFF, #4B44C4)' },
    href: '/work/pulse',
    links: {
      caseStudy: '/work/pulse',
      demo: 'https://pulse-ai-crm.vercel.app/',
      code: 'https://github.com/yash-vks-chauhan/Pulse',
    },
    featured: true,
    sources: ['pulse-architecture', 'pulse-tests'],
  },
  {
    slug: 'gridee',
    name: 'Gridee',
    guarantee: 'Smart parking I co-founded, with 8,000+ combined Android and iOS downloads.',
    short: 'Smart parking I co-founded: 8,000+ downloads.',
    tagline: '8,000+ downloads',
    summary: 'Live availability, advance and instant reservations, wallet and Razorpay payments, and QR or number-plate check-in.',
    status: 'in-stores',
    categories: ['mobile'],
    stack: ['Kotlin', 'CameraX', 'ML Kit', 'Razorpay'],
    year: '2026–',
    icon: { image: 'gridee-icon' },
    href: '/work/gridee',
    links: {
      caseStudy: '/work/gridee',
      site: 'https://www.gridee.in/',
      playStore: 'https://play.google.com/store/apps/details?id=com.gridee.parking',
      appStore: 'https://apps.apple.com/us/app/grideeapp/id6757460398',
    },
    featured: true,
    sources: ['gridee-downloads'],
  },
  {
    slug: 'ems-research',
    name: 'EMS operational drift',
    guarantee: 'IIT Madras research: real operational drift, separated from context a district can’t control.',
    short: 'IIT Madras: real drift, separated from context a district can’t control.',
    tagline: 'IIT Madras',
    summary: 'Graph embeddings, a VAE and counterfactual XGBoost, then an equity check on who bears the burden.',
    status: 'manuscript',
    categories: ['research'],
    stack: ['GraphSAGE', 'VAE', 'XGBoost', 'SHAP'],
    year: '2025–26',
    icon: { glyph: 'ambulance', gradient: 'linear-gradient(145deg, #FF6B6B, #D7263D)' },
    href: '/work/ems-research',
    links: { caseStudy: '/work/ems-research' },
    sources: ['iitm-internship'],
  },
  {
    slug: 'ieee-manuscript',
    name: 'First-author manuscript',
    guarantee: 'Under double-blind review at an IEEE conference (2026).',
    short: 'Under double-blind review at an IEEE conference (2026).',
    tagline: 'IEEE conference, double-blind',
    summary: 'Details after the decision.',
    status: 'double-blind',
    categories: ['research'],
    stack: [],
    meta: 'Details after the decision',
    year: '2026',
    icon: { glyph: 'lock', gradient: 'linear-gradient(145deg, #8E8BFF, #5149C9)' },
    href: '/research#ieee-manuscript',
    links: {},
  },
  {
    slug: 'autoscaler',
    name: 'Autoscaler',
    guarantee: 'Guarded Kubernetes self-healing: dry-run, cooldowns, a circuit breaker and an approval gate on every action.',
    short: 'Guarded self-healing: dry-run, cooldowns, a circuit breaker, an approval gate.',
    tagline: 'Guarded Kubernetes self-healing',
    summary: 'Detect, explain and act, with safety rails around every healing action.',
    status: 'in-progress',
    categories: ['ai-systems'],
    stack: ['NestJS', 'FastAPI', 'Kubernetes'],
    meta: 'NestJS · FastAPI · Kubernetes · LSTM planned',
    year: '2026',
    icon: { glyph: 'gauge', gradient: 'linear-gradient(145deg, #64D2FF, #0A7CFF)' },
    href: '/work/autoscaler',
    links: { code: 'https://github.com/yash-vks-chauhan/Autoscaler' },
    sources: ['autoscaler-readme'],
  },
  {
    slug: 'kalakraft',
    name: 'Kalakraft',
    guarantee: 'I audited my own shipped marketplace and fixed six critical security issues.',
    short: 'I audited my own shipped marketplace and fixed six critical issues.',
    tagline: 'Self-audit: six critical fixes',
    summary: 'A Next.js storefront and admin with 59 API routes and 20 Prisma models.',
    status: 'live',
    categories: ['full-stack'],
    stack: ['Next.js', 'Prisma', 'Firebase Auth'],
    year: '2025',
    icon: { glyph: 'palette', gradient: 'linear-gradient(145deg, #FFB340, #FF5E3A)' },
    href: '/work/kalakraft',
    links: {
      demo: 'https://kalakraftdev.vercel.app',
      code: 'https://github.com/yash-vks-chauhan/Kalakraftdev',
    },
    sources: ['kalakraft-security'],
  },
  {
    slug: 'ct-denoising',
    name: 'CT denoising U-Net',
    guarantee: 'An early learning project. Metrics withheld while the data pairing is re-checked.',
    short: 'An early learning project. Metrics withheld while the data pairing is re-checked.',
    tagline: 'Metrics withheld, re-checking',
    summary: 'A TensorFlow/Keras U-Net for heavy synthetic noise.',
    status: 'on-hold',
    categories: ['experiments'],
    stack: ['TensorFlow', 'Keras'],
    year: '2025',
    icon: { glyph: 'scan-line', gradient: 'linear-gradient(145deg, #AEAEB2, #636366)' },
    href: '/work/ct-denoising',
    links: { code: 'https://github.com/yash-vks-chauhan/CT-Denoising-U-Net' },
  },
];

export const categoryLabels: Record<string, string> = {
  'ai-systems': 'AI systems',
  'full-stack': 'Full-stack',
  research: 'Research',
  mobile: 'Mobile',
  experiments: 'Experiments',
};

export const projectBySlug: Record<string, (typeof projects)[number]> = Object.fromEntries(projects.map((p) => [p.slug, p]));

/** The work-index meta line: "FastAPI · Next.js · Postgres · 2026". */
export function projectMeta(p: (typeof projects)[number]): string {
  // Versions stay on the cards ("Next.js 16") but not in the meta line ("Next.js"), as drawn.
  return p.meta ?? [...p.stack.slice(0, 3).map((s) => s.replace(/ \d+$/, '')), p.year].join(' · ');
}
