// The eight projects, in the order the work index shows them ("sorted by how much they prove").
// Categories give the work-index counts: AI systems 3 · Full-stack 3 · Research 2 · Mobile 1 · Experiments 1.
import type { Project } from './types';

export const projects: Project[] = [
  {
    slug: 'glassbox',
    name: 'GlassBox',
    guarantee: 'Every answer is cited or refused; every decision is hash-chained per tenant.',
    summary: 'Auditable wealth-advisory AI.',
    status: 'live',
    categories: ['ai-systems', 'full-stack'],
    stack: ['FastAPI', 'Next.js 16', 'Postgres', 'scikit-learn'],
    year: '2026',
    icon: { glyph: 'box', gradient: 'linear-gradient(150deg, #2F6BFF 0%, #1E3A8A 60%, #0B1F4D 100%)' },
    links: {
      caseStudy: '/work/glassbox',
      demo: 'https://glassbox.15-252-203-137.sslip.io',
      code: 'https://github.com/yash-vks-chauhan/Glassbox',
      video: '[90-second demo video]',
    },
    featured: true,
    sources: ['glassbox-eval-v4', 'glassbox-ci', 'glassbox-deploy'],
    todo: ['Your role on the case study (solo build?)', 'A real domain for the demo instead of sslip.io', 'The "Over" alternative in each decision'],
  },
  {
    slug: 'pulse',
    name: 'Pulse',
    guarantee: 'The LLM proposes a validated DSL. It never writes SQL, touches the database or sees PII.',
    summary: 'AI-native campaign CRM.',
    status: 'live',
    categories: ['ai-systems', 'full-stack'],
    stack: ['NestJS', 'BullMQ', 'Prisma'],
    year: '2026',
    icon: { glyph: 'activity', gradient: 'linear-gradient(145deg, #8E8BFF, #4B44C4)' },
    links: {
      caseStudy: '/work/pulse',
      demo: 'https://pulse-ai-crm.vercel.app/',
      code: 'https://github.com/yash-vks-chauhan/Pulse',
    },
    featured: true,
    sources: ['pulse-architecture', 'pulse-tests'],
    todo: ['Confirm the Xeno assignment terms allow public posting', 'Make the README and ARCHITECTURE.md agree on the LLM provider chain'],
  },
  {
    slug: 'gridee',
    name: 'Gridee',
    guarantee: 'Smart parking I co-founded, with 8,000+ combined Android and iOS downloads.',
    summary: 'Live availability, advance and instant reservations, wallet and Razorpay payments, and QR or number-plate check-in.',
    status: 'in-stores',
    categories: ['mobile'],
    stack: ['Kotlin', 'CameraX', 'ML Kit', 'Razorpay'],
    year: '2026–',
    icon: { image: '/images/gridee-icon.png' },
    links: {
      site: 'https://www.gridee.in/',
      playStore: 'https://play.google.com/store/apps/details?id=com.gridee.parking',
      appStore: 'https://apps.apple.com/us/app/grideeapp/id6757460398',
    },
    featured: true,
    sources: ['gridee-downloads'],
    todo: ['Your role split with your co-founder', 'Whether 8,000+ counts downloads or active users'],
  },
  {
    slug: 'ems-research',
    name: 'EMS operational drift',
    guarantee: 'IIT Madras research: real operational drift, separated from context a district can’t control.',
    summary: 'Graph embeddings, a VAE and counterfactual XGBoost, then an equity check on who bears the burden.',
    status: 'manuscript',
    categories: ['research'],
    stack: ['GraphSAGE', 'VAE', 'XGBoost', 'SHAP'],
    year: '2025–26',
    icon: { glyph: 'ambulance', gradient: 'linear-gradient(145deg, #FF6B6B, #D7263D)' },
    links: {},
    sources: ['iitm-internship'],
    todo: ['Confirm the venue and review status', 'Ask the PI what you may show (aggregate results only; government data)'],
  },
  {
    slug: 'ieee-manuscript',
    name: 'First-author manuscript',
    guarantee: 'Under double-blind review at an IEEE conference (2026).',
    summary: 'Details after the decision.',
    status: 'double-blind',
    categories: ['research'],
    stack: [],
    year: '2026',
    icon: { glyph: 'lock', gradient: 'linear-gradient(145deg, #8E8BFF, #5149C9)' },
    links: {},
    todo: ['No title, topic or PDF until the decision', 'After acceptance: "Accepted, IEEE DELCON 2026 (to appear)"'],
  },
  {
    slug: 'autoscaler',
    name: 'Autoscaler',
    guarantee: 'Guarded Kubernetes self-healing: dry-run, cooldowns, a circuit breaker and an approval gate on every action.',
    summary: 'Detect, explain and act, with safety rails around every healing action.',
    status: 'in-progress',
    categories: ['ai-systems'],
    stack: ['NestJS', 'FastAPI', 'Kubernetes'],
    year: '2026',
    icon: { glyph: 'gauge', gradient: 'linear-gradient(145deg, #64D2FF, #0A7CFF)' },
    links: { code: 'https://github.com/yash-vks-chauhan/Autoscaler' },
    sources: ['autoscaler-readme'],
    todo: ['Add tests on the safety rails', 'Say "SHAP-style attribution", not SHAP; the LSTM is planned, not built'],
  },
  {
    slug: 'kalakraft',
    name: 'Kalakraft',
    guarantee: 'I audited my own shipped marketplace and fixed six critical security issues.',
    summary: 'A Next.js storefront and admin with 59 API routes and 20 Prisma models.',
    status: 'live',
    categories: ['full-stack'],
    stack: ['Next.js', 'Prisma', 'Firebase Auth'],
    year: '2025',
    icon: { glyph: 'palette', gradient: 'linear-gradient(145deg, #FFB340, #FF5E3A)' },
    links: {
      demo: 'https://kalakraftdev.vercel.app',
      code: 'https://github.com/yash-vks-chauhan/Kalakraftdev',
    },
    sources: ['kalakraft-security'],
    todo: ['Clarify ownership and whether it has real orders'],
  },
  {
    slug: 'ct-denoising',
    name: 'CT denoising U-Net',
    guarantee: 'An early learning project. Metrics withheld while the data pairing is re-checked.',
    summary: 'A TensorFlow/Keras U-Net for heavy synthetic noise.',
    status: 'on-hold',
    categories: ['experiments'],
    stack: ['TensorFlow', 'Keras'],
    year: '2025',
    icon: { glyph: 'scan-line', gradient: 'linear-gradient(145deg, #AEAEB2, #636366)' },
    links: { code: 'https://github.com/yash-vks-chauhan/CT-Denoising-U-Net' },
    todo: ['Fix the noisy/clean pairing and re-run the metrics before quoting any number'],
  },
];

export const categoryLabels: Record<string, string> = {
  'ai-systems': 'AI systems',
  'full-stack': 'Full-stack',
  research: 'Research',
  mobile: 'Mobile',
  experiments: 'Experiments',
};
