// Lucide glyphs named in the content files (project icons, certification icons, constraint icons).
// Explicit imports keep islands small: only these icons ship.
import {
  Activity,
  Ambulance,
  Ban,
  Box,
  Car,
  CircleCheck,
  Cloud,
  Cpu,
  Database,
  Eye,
  FileSearch,
  Gauge,
  GitBranch,
  GraduationCap,
  KeyRound,
  Layers,
  Link,
  List,
  Lock,
  MessageCircle,
  Palette,
  Quote,
  RefreshCw,
  Repeat,
  ScanLine,
  Send,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

export const glyphs: Record<string, LucideIcon> = {
  activity: Activity,
  ambulance: Ambulance,
  ban: Ban,
  box: Box,
  car: Car,
  'circle-check': CircleCheck,
  cloud: Cloud,
  cpu: Cpu,
  database: Database,
  eye: Eye,
  'file-search': FileSearch,
  gauge: Gauge,
  'git-branch': GitBranch,
  'graduation-cap': GraduationCap,
  'key-round': KeyRound,
  layers: Layers,
  link: Link,
  list: List,
  lock: Lock,
  'message-circle': MessageCircle,
  palette: Palette,
  quote: Quote,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  'scan-line': ScanLine,
  send: Send,
  'shield-check': ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  users: Users,
  wallet: Wallet,
};

export function glyph(name: string): LucideIcon {
  const g = glyphs[name];
  if (!g) throw new Error(`Unknown glyph "${name}". Add it to src/components/ui/glyphs.ts.`);
  return g;
}
