#!/usr/bin/env node
// Writes ../tokens/tokens.css, ../tokens/tokens.json and ../tokens/tailwind.css from tokens.js.
// usage: node gen-tokens.js
const fs = require('fs');
const path = require('path');
const T = require('./tokens.js');

const OUT = path.join(__dirname, '..', 'tokens');
const HEADER = '/* Glass design tokens. Generated by design/source/gen-tokens.js from tokens.js; edit those, not this file. */';

const decls = (map, indent = '  ') => Object.entries(map).map(([k, v]) => `${indent}--${k}: ${v};`).join('\n');
const shared = [
  `  --font-system: ${T.font.system};`,
  `  --font-rounded-stack: ${T.font.rounded};`,
  `  --font-mono-stack: ${T.font.mono};`,
  ...Object.entries(T.radius).map(([k, v]) => `  --r-${k}: ${v};`),
  `  --container: ${T.layout.container};`,
  `  --gutter: ${T.layout.gutter};`,
  `  --gutter-phone: ${T.layout.gutterPhone};`,
  `  --section-gap: ${T.layout.section};`,
  `  --section-gap-phone: ${T.layout.sectionPhone};`,
  `  --ease-out: ${T.motion.ease};`,
  `  --lift-distance: ${T.motion.lift.distance};`,
  `  --lift-duration: ${T.motion.lift.duration};`,
].join('\n');

function accentBlocks(themeSelector, themeKey, indent = '') {
  return Object.entries(T.accent)
    .filter(([name]) => name !== 'Blue')
    .map(([name, a]) => `${indent}${themeSelector}[data-accent="${name.toLowerCase()}"] {\n${decls(a[themeKey], indent + '  ')}\n${indent}}`)
    .join('\n');
}

const css = `${HEADER}
/* Light is the default; [data-theme="dark"] switches everything. Without JS, the OS setting decides.
   Accent: Blue by default; set data-accent="indigo" or "graphite" on <html> for the alternatives. */

:root {
  color-scheme: light;
${decls(T.color.Light)}
${decls(T.accent.Blue.Light)}
${shared}
}

[data-theme="dark"] {
  color-scheme: dark;
${decls(T.color.Dark)}
${decls(T.accent.Blue.Dark)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${decls(T.color.Dark, '    ')}
${decls(T.accent.Blue.Dark, '    ')}
  }
${accentBlocks(':root:not([data-theme="light"])', 'Dark', '  ')}
}

${accentBlocks(':root', 'Light')}
${accentBlocks('[data-theme="dark"]', 'Dark')}

html {
  background: var(--bg);
}

body {
  margin: 0;
  background: var(--bg);
  color: var(--label);
  font-family: var(--font-system);
  font-size: 17px; /* on body, not html, so rem-based spacing stays 4 px per step */
  line-height: 1.47;
  letter-spacing: -0.022em;
  -webkit-font-smoothing: antialiased;
}

:focus-visible {
  outline: 3px solid color-mix(in srgb, var(--blue) 50%, transparent);
  outline-offset: 3px;
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after { animation-duration: 0.01ms !important; animation-iteration-count: 1 !important; transition-duration: 0.01ms !important; scroll-behavior: auto !important; }
}
`;

const typeTheme = Object.entries(T.type)
  .map(([k, t]) => [
    `  --text-${k}: ${t.size}px;`,
    `  --text-${k}--line-height: ${t.line};`,
    `  --text-${k}--letter-spacing: ${t.tracking}em;`,
    `  --text-${k}--font-weight: ${t.weight};`,
  ].join('\n'))
  .join('\n');

const tailwind = `/* Glass → Tailwind CSS v4. Generated by design/source/gen-tokens.js; edit tokens.js, not this file.
   In your global stylesheet:
     @import "tailwindcss";
     @import "./tokens.css";
     @import "./tailwind.css";
*/

@custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));

@theme inline {
  --color-bg: var(--bg);
  --color-card: var(--card);
  --color-fill: var(--fill);
  --color-fill2: var(--fill2);
  --color-label: var(--label);
  --color-label2: var(--label2);
  --color-label3: var(--label3);
  --color-ink2: var(--ink2);
  --color-sep: var(--sep);
  --color-hair: var(--hair);
  --color-accent: var(--blue);
  --color-on-accent: var(--on-accent);
  --color-link: var(--link);
  --color-cite: var(--cite);
  --color-cite-wash: var(--blue-wash);
  --color-ok: var(--ok);
  --color-ok-wash: var(--ok-wash);
  --color-warn: var(--warn);
  --color-warn-wash: var(--warn-wash);
  --color-mute: var(--mute);
  --color-mute-wash: var(--mute-wash);
  --color-chip: var(--chip);
  --color-chip-ink: var(--chip-ink);
  --color-seg-on: var(--seg-on);
  --font-sans: var(--font-system);
  --font-rounded: var(--font-rounded-stack);
  --font-mono: var(--font-mono-stack);
}

@theme {
  --radius-card: ${T.radius.card};
  --radius-card-phone: ${T.radius['card-phone']};
  --radius-widget: ${T.radius.widget};
  --radius-widget-phone: ${T.radius['widget-phone']};
  --radius-list: ${T.radius.list};
  --radius-field: ${T.radius.field};
  --radius-icon: ${T.radius.icon};
  --ease-glass: ${T.motion.ease};
${typeTheme}
}

/* Elevation */
@utility elev-resting { box-shadow: var(--shadow-sm); }
@utility elev-raised { box-shadow: var(--shadow); }
@utility elev-floating { box-shadow: var(--shadow-lg); }

/* Materials: only for things that float above content (nav, widgets over the hero, sheets, dock, tab bar) */
@utility glass-thin {
  background: var(--glass);
  -webkit-backdrop-filter: blur(24px) saturate(180%);
  backdrop-filter: blur(24px) saturate(180%);
  border: 1px solid var(--glass-border);
  box-shadow: inset 0 1px 0 var(--glass-hi), var(--shadow);
}
@utility glass-regular {
  background: var(--glass-w);
  -webkit-backdrop-filter: blur(30px) saturate(190%);
  backdrop-filter: blur(30px) saturate(190%);
  border: 1px solid var(--glass-border);
  box-shadow: inset 0 1px 0 var(--glass-hi), var(--shadow);
}
@utility glass-strong {
  background: var(--glass-strong);
  -webkit-backdrop-filter: blur(30px) saturate(180%);
  backdrop-filter: blur(30px) saturate(180%);
  box-shadow: inset 0 0 0 1px var(--hair), var(--shadow-lg);
}

/* Card lift on hover (off under reduced motion) */
@utility lift {
  transition: transform var(--lift-duration) var(--ease-out);
  &:hover { transform: translateY(calc(var(--lift-distance) * -1)); }
  @media (prefers-reduced-motion: reduce) { &:hover { transform: none; } }
}
`;

const json = {
  $description: 'Glass design tokens for the Yash Chauhan portfolio. Generated from design/source/tokens.js.',
  color: { light: T.color.Light, dark: T.color.Dark },
  accent: Object.fromEntries(Object.entries(T.accent).map(([k, v]) => [k.toLowerCase(), { light: v.Light, dark: v.Dark }])),
  font: T.font,
  type: T.type,
  radius: T.radius,
  space: T.space,
  layout: T.layout,
  material: T.material,
  motion: T.motion,
};

fs.writeFileSync(path.join(OUT, 'tokens.css'), css);
fs.writeFileSync(path.join(OUT, 'tailwind.css'), tailwind);
fs.writeFileSync(path.join(OUT, 'tokens.json'), JSON.stringify(json, null, 2) + '\n');
console.log('wrote tokens/tokens.css, tokens/tailwind.css, tokens/tokens.json');
