// GlassBox, as drawn on the case-study artboards (design/prototype GlassCase.html, GlassMobileCaseDark.html).
// Facts: the README's GlassBox deep-dive and design/starter/content. Intervals come from lib/wilson.ts.
import type { CaseStudy } from './types';
import { formatInterval, wilson } from '../../lib/wilson';

const ci = (k: number, n: number) => formatInterval(wilson(k, n));
const correct = wilson(183, 183);
const hallucinations = wilson(0, 183);

export const glassbox: CaseStudy = {
  slug: 'glassbox',
  title: 'GlassBox · Yash Chauhan',
  description:
    'GlassBox is auditable wealth-advisory AI: every answer is cited to an approved document or refused, and every decision is hash-chained per tenant. 183/183 on a development set, with the caveat.',
  name: 'GlassBox',
  lead: 'Auditable wealth-advisory AI. Every answer is cited or refused, and every decision is hash-chained per tenant.',
  leadPhone: 'Auditable wealth-advisory AI',
  icon: { glyph: 'box', gradient: 'radial-gradient(120% 120% at 20% 0%, #6EA8FF 0%, rgba(110,168,255,0) 55%), linear-gradient(150deg, #2F6BFF 0%, #1E3A8A 60%, #0B1F4D 100%)' },
  actions: [
    { label: 'Open demo', labelPhone: 'Open', href: 'https://glassbox.15-252-203-137.sslip.io', kind: 'demo', primary: true },
    { label: 'Code', href: 'https://github.com/yash-vks-chauhan/Glassbox', kind: 'code' },
    { label: 'Watch 90 s', href: '[90-second demo video]', kind: 'video', desktopOnly: true },
  ],
  note: 'The demo runs on one small instance; the first load can take about 45 seconds.',
  stats: [
    { label: 'Eval accuracy', labelPhone: 'Eval', value: '183/183', note: `95% CI ${ci(183, 183)}`, notePhone: `CI ${ci(183, 183)}` },
    { label: 'Hallucinations', value: '0/183', note: `95% CI ${ci(0, 183)}`, notePhone: `CI ${ci(0, 183)}` },
    { label: 'Tests', value: '254', note: 'backend, plus 11 e2e', notePhone: '+ 11 e2e' },
    { label: 'p95 latency', labelPhone: 'p95', value: '1 ms', note: 'local evidence engine', notePhone: 'local engine' },
    { label: 'Hosting', value: '~$14', note: 'a month on AWS', notePhone: 'a month' },
    { label: 'Licence', value: 'MIT', note: 'open source' },
  ],
  preview: {
    slides: [
      {
        image: 'glassbox-ask',
        alt: 'An advisor’s question answered with numbered citations and a compliance flag',
        title: 'Ask.',
        caption: 'Every claim carries a numbered citation; the answer is flagged against the client’s IPS.',
        captionPhone: 'Every claim cited; flagged against the IPS.',
      },
      {
        image: 'glassbox-refusal',
        alt: 'An out-of-scope question refused, with the missing source named',
        title: 'Refuse.',
        caption: 'Out of scope: refused, the missing source named, one click to escalate.',
        captionPhone: 'The missing source, named.',
      },
      {
        image: 'glassbox-audit-replay',
        alt: 'Decision replay showing the answer, claim audit, trust scores and row hash',
        title: 'Replay.',
        caption: 'Any decision: the answer, its claim audit, trust scores and the row hash.',
        captionPhone: 'Claims, scores, row hash.',
      },
      {
        image: 'glassbox-audit-log',
        alt: 'The per-tenant audit log',
        title: 'Audit log.',
        caption: 'Per tenant, hash-chained; the database refuses DELETE.',
        captionPhone: 'Per tenant, hash-chained.',
      },
    ],
  },
  summary: {
    icon: 'sparkles',
    gradient: 'linear-gradient(145deg, #5AC8FA, #0A7CFF)',
    text: `On 183 questions I wrote alongside the engine, GlassBox answered or refused correctly every time (95% CI ${ci(183, 183)}). That’s a development set, not an independent benchmark.{{cite:glassbox-eval-v4}}`,
    textPhone: `On 183 questions I wrote alongside the engine, GlassBox answered or refused correctly every time (95% CI ${ci(183, 183)}). A development set, not an independent benchmark.{{cite:glassbox-eval-v4}}`,
  },
  sections: [
    {
      kind: 'prose',
      id: 'problem',
      title: 'Problem',
      phone: 1,
      paragraphs: [
        'Wealth advisors answer client questions under suitability rules. A wrong answer is a compliance problem, and a confident wrong answer is worse. A general chat assistant can’t show where an answer came from, and it rarely says “I don’t know”.',
        'GlassBox answers only from a client’s approved documents (the investment policy statement, fund factsheets and regulation) and refuses everything else. A compliance seat reviews flagged answers under a four-eyes rule.',
      ],
      paragraphsPhone: [
        'Advisors answer clients under suitability rules. A confident wrong answer is a compliance problem, and a chat assistant can’t show where an answer came from. GlassBox answers only from a client’s approved documents and refuses everything else.',
      ],
    },
    {
      kind: 'constraints',
      id: 'constraints',
      title: 'Constraints',
      phone: 'more',
      items: [
        { icon: 'quote', gradient: 'linear-gradient(145deg, #5AC8FA, #0A7CFF)', title: 'Cite approved documents only.', text: 'Anything else is refused, with the missing source named.' },
        { icon: 'refresh-cw', gradient: 'linear-gradient(145deg, #8E8BFF, #5149C9)', title: 'Replayable.', text: 'Every decision can be replayed later, by someone else.' },
        { icon: 'layers', gradient: 'linear-gradient(145deg, #4CD964, #1F8F3A)', title: 'Multi-tenant.', text: 'One firm’s data and audit chain never touch another’s.' },
        { icon: 'cpu', gradient: 'linear-gradient(145deg, #FFB340, #F08A00)', title: 'Small and cheap.', text: 'Runs on one small instance for about $14 a month.' },
      ],
    },
    {
      kind: 'architecture',
      id: 'architecture',
      title: 'Architecture',
      titlePhone: 'How an answer is made',
      phone: 2,
      intro: 'Every path ends in the audit log. A claim the scorers can’t ground turns the answer into a refusal.',
      diagram: {
        width: 780,
        height: 456,
        nodes: [
          { x: 8, y: 24, icon: 'message-circle', bold: 'Advisor asks', text: 'about a client' },
          { x: 206, y: 24, icon: 'file-search', bold: 'Retrieve', text: 'approved docs only' },
          { x: 404, y: 24, icon: 'list', bold: 'Draft', text: 'the answer as claims' },
          { x: 602, y: 24, icon: 'gauge', bold: 'Score', text: 'every claim' },
          { x: 404, y: 184, icon: 'ban', tone: 'warn', bold: 'Refuse:', text: 'name the missing source' },
          { x: 602, y: 184, icon: 'circle-check', tone: 'ok', bold: 'Answer,', text: 'every claim cited' },
          { x: 503, y: 344, icon: 'link', tone: 'cite', bold: 'Audit log,', text: 'hash‑chained, no DELETE' },
          { x: 305, y: 344, icon: 'eye', bold: 'Compliance', text: 'four‑eyes review' },
        ],
        edges: [
          { x: 158, y: 64, len: 46, dir: 'right', arrow: true },
          { x: 356, y: 64, len: 46, dir: 'right', arrow: true },
          { x: 554, y: 64, len: 46, dir: 'right', arrow: true },
          { x: 673, y: 112, len: 36, dir: 'down' },
          { x: 479, y: 144, len: 198, dir: 'right' },
          { x: 475, y: 148, len: 34, dir: 'down', arrow: true },
          { x: 673, y: 148, len: 34, dir: 'down', arrow: true },
          { x: 475, y: 272, len: 36, dir: 'down' },
          { x: 673, y: 272, len: 36, dir: 'down' },
          { x: 479, y: 304, len: 198, dir: 'right' },
          { x: 574, y: 308, len: 34, dir: 'down', arrow: true },
          { x: 457, y: 384, len: 46, dir: 'left', arrow: true },
        ],
        labels: [
          { x: 433, y: 120, w: 92, text: 'unsupported', tone: 'warn', align: 'center' },
          { x: 689, y: 122, w: 76, text: 'supported', tone: 'ok', align: 'left' },
          {
            x: 8,
            y: 200,
            w: 330,
            size: 'note',
            text: 'Three small scikit-learn models do the scoring: grounding, a refusal router and a fallback classifier. No LLM judges the LLM.',
          },
        ],
        text: 'Text version: a question retrieves passages from approved documents only; the draft is split into claims and each is scored. Unsupported claims trigger a refusal that names the missing source; supported ones form a cited answer. Both are appended to a per-tenant, hash-chained audit log that compliance reviews.',
      },
      steps: [
        { text: '**Advisor asks** about a client' },
        { text: '**Retrieve** approved documents only' },
        { text: '**Draft** the answer as claims, and **score** each one' },
        { text: '**Supported:** answer, every claim cited', tone: 'ok', icon: 'circle-check' },
        { text: '**Unsupported:** refuse, naming the missing source', tone: 'warn', icon: 'ban' },
        { text: '**Either way:** appended to a hash-chained audit log; compliance reviews flags', tone: 'cite', icon: 'link' },
      ],
    },
    {
      kind: 'decisions',
      id: 'decisions',
      title: 'Decisions',
      phone: 4,
      items: [
        {
          title: 'Refuse instead of guessing',
          chose: 'Out-of-scope questions are refused. The refusal names the missing source and offers one-click escalation to compliance.',
          over: '[The alternative you weighed, e.g. answering with a disclaimer]',
          because: 'An advisor can act on a refusal. They can’t check a guess.',
          cost: 'Lower coverage, and more escalations for compliance to handle.',
          costPhone: 'Lower coverage, and more escalations for compliance.',
        },
        {
          title: 'Small scikit-learn scorers, not an LLM judge',
          chose: 'Three small models: a grounding scorer (logistic regression on embedding similarity plus numeric match), a refusal router and a fallback classifier.',
          over: '[An LLM-as-judge, or another option you tried]',
          because: 'Deterministic and fast: determinism 1.00 and p95 latency 1 ms on the benchmark.',
          cost: 'Small training sets (320 / 240 / 160 rows), synthetic or bootstrapped.',
        },
        {
          title: 'Hash-chain the log per tenant; forbid DELETE',
          chose: 'Each decision is stored with its passages, kept and dropped claims and trust scores, and chained per tenant. The database refuses DELETE on audit tables.',
          over: '[Application-level logging only, or the option you weighed]',
          because: 'Tampering becomes detectable, and any answer can be replayed.',
          cost: 'Tamper-evident, not tamper-proof, until the chain head is anchored outside the system.',
        },
      ],
    },
    {
      kind: 'evaluation',
      id: 'evaluation',
      title: 'Evaluation',
      phone: 3,
      evaluation: {
        intro: 'glassbox-eval-v4, run on 2 Oct 2026: 183 questions written alongside the engine. Intervals are Wilson 95%.{{cite:glassbox-eval-v4}}',
        introPhone: 'glassbox-eval-v4, 2 Oct 2026. Wilson 95% intervals.',
        ring: {
          k: 183,
          n: 183,
          title: 'Answered or refused correctly',
          caption: `Answered or refused correctly. 95% CI ${ci(183, 183)}.`,
          notePhone: `95% CI ${ci(183, 183)}. Read it as “no failures found yet”.`,
        },
        metrics: [
          { label: 'Outcome accuracy', note: `CI ${ci(183, 183).replace('%', '')}, on a 90–100 scale`, value: '183/183', bar: { from: (correct.lower * 100 - 90) / 10, to: 1 } },
          { label: 'Citation accuracy', note: `CI ${ci(183, 183).replace('%', '')}, on a 90–100 scale`, value: '183/183', bar: { from: (correct.lower * 100 - 90) / 10, to: 1 } },
          { label: 'Hallucination rate', note: `CI ${ci(0, 183).replace('%', '')}, on a 0–10 scale`, value: '0/183', bar: { from: 0, to: (hallucinations.upper * 100) / 10 } },
          { label: 'Faithfulness', note: 'A score, not a proportion', value: '0.98' },
          { label: 'Determinism', note: 'Same answer on repeat runs', value: '1.00' },
          { label: 'p95 latency', note: 'Local evidence engine', value: '1 ms' },
        ],
        phoneRows: [
          { label: 'Hallucination rate', value: '0/183', note: `· CI ${ci(0, 183)}` },
          { label: 'Citation accuracy', value: '183/183' },
          { label: 'Faithfulness', value: '0.98' },
          { label: 'Determinism', value: '1.00' },
          { label: 'p95 latency', value: '1 ms' },
        ],
        caveat:
          '**A development set, not a held-out benchmark.** I wrote the questions while building the engine, so read 100% as “no failures found yet”, not “perfect”. Per-category results and the over-refusal rate come next.',
        caveatPhone: 'I wrote the questions while building the engine, so this is a development set, not a held-out benchmark.',
        reproduce: { command: 'make eval', comment: '# [confirm the real command]', output: 'glassbox-eval-v4 · 183 questions · 183 correct · p95 1 ms' },
      },
    },
    {
      kind: 'ops',
      id: 'ops',
      title: 'Tests & ops',
      phone: 'more',
      ops: {
        cards: [
          { value: '254', cite: 'glassbox-ci', text: 'backend tests on Postgres 15 (249 on SQLite; 5 are Postgres-only)' },
          { value: '11', text: 'Playwright end-to-end specs' },
          { value: '~$14', cite: 'glassbox-deploy', text: 'a month on one Graviton t4g.small in Mumbai' },
        ],
        chainTitle: 'Every push',
        chain: [
          { label: 'push', icon: 'git-branch' },
          { label: 'CI · SQLite + Postgres 15' },
          { label: 'Docker smoke test' },
          { label: 'AWS via OIDC, no stored keys' },
          { label: 'arm64 image → ECR' },
          { label: 'rollout over SSM' },
          { label: 'smoke test', icon: 'circle-check', tone: 'ok' },
        ],
        note: 'Also in the repo: a STRIDE threat model mapped to code and tests, 14 runbooks, TOTP MFA, rotating refresh tokens with reuse detection, and prompt-injection containment.',
      },
    },
    {
      kind: 'list',
      id: 'limits',
      title: 'What broke, and the limits',
      toc: 'What broke',
      phone: 'more',
      tone: 'warn',
      items: [
        { text: 'The benchmark is author-written, so it can’t measure what I didn’t think to test.' },
        { text: 'The scorers learned from small, synthetic or bootstrapped sets. Reviewer labels are now exported so they can be retrained on real judgments.' },
        { text: 'The hash chain is tamper-evident, not tamper-proof: the chain head isn’t anchored outside the system yet.' },
        { text: '[A real bug you hit: how you found it and what changed]', placeholder: true },
      ],
    },
    {
      kind: 'next',
      id: 'next',
      title: 'What I’d do next',
      toc: 'Next',
      phone: 'more',
      items: [
        { status: 'Planned', text: 'Anchor the chain head outside the system, for example as a signed daily digest.' },
        { status: 'Planned', text: 'Move retrieval from the NumPy index to pgvector, and retrain the scorers on reviewer labels.' },
        { status: 'Planned', text: 'Report per-category pass rates with intervals, and the over-refusal rate.' },
      ],
    },
    {
      kind: 'ai-note',
      id: 'ai-note',
      title: 'How I used AI tools',
      toc: 'AI-tool note',
      phone: 'more',
      text: '[What you delegated to AI tools on GlassBox, which decisions stayed yours, and one thing you caught and corrected in review.]',
    },
  ],
  info: [
    { label: 'Role', value: '[Your role, e.g. solo build]', valuePhone: '[Your role]', phone: true },
    { label: 'Timeline', value: 'Feb – Oct 2026', phone: true },
    { label: 'Stack', value: 'FastAPI · Next.js 16 · Postgres · scikit-learn', valuePhone: 'FastAPI · Next.js 16 · Postgres', phone: true },
    { label: 'Infrastructure', labelPhone: 'Infra', value: 'AWS t4g.small · OIDC deploys', valuePhone: 'AWS t4g.small · OIDC', phone: true },
    { label: 'Size', value: '~16.6k lines API · ~14k lines web' },
    { label: 'Access', value: 'Owner, admin, compliance, advisor roles · TOTP MFA' },
    { label: 'Licence', value: 'MIT', phone: true },
    { label: 'Repository', value: 'github.com/yash-vks-chauhan/Glassbox', href: 'https://github.com/yash-vks-chauhan/Glassbox' },
  ],
  sources: ['glassbox-eval-v4', 'glassbox-ci', 'glassbox-deploy', 'glassbox-screenshots', 'glassbox-demo'],
  more: ['pulse', 'gridee'],
};
