// Pulse, on the GlassBox template. Facts: the README's Pulse deep-dive and design/starter/content (sources.ts lists
// where each one lives). The demo values (₹2,000, 60 days, 1,284 customers) come from the demo's seeded data.
import type { CaseStudy } from './types';

export const pulse: CaseStudy = {
  slug: 'pulse',
  title: 'Pulse · Yash Chauhan',
  description:
    'Pulse is an AI-native campaign CRM: the LLM proposes a validated Segment DSL and never writes SQL, touches the database or sees PII. Delivery is tested with a 1,000-message run under injected chaos.',
  name: 'Pulse',
  lead: 'AI-native campaign CRM. The LLM proposes a validated DSL; it never writes SQL, touches the database or sees PII.',
  leadPhone: 'AI-native campaign CRM',
  icon: { glyph: 'activity', gradient: 'radial-gradient(120% 120% at 20% 0%, #B3B0FF 0%, rgba(179,176,255,0) 55%), linear-gradient(150deg, #8E8BFF 0%, #4B44C4 60%, #2A2580 100%)' },
  actions: [
    { label: 'Open demo', labelPhone: 'Open', href: 'https://pulse-ai-crm.vercel.app/', kind: 'demo', primary: true },
    { label: 'Code', href: 'https://github.com/yash-vks-chauhan/Pulse', kind: 'code' },
  ],
  note: 'The demo sits behind a login gate; the access code is on the login screen.',
  stats: [
    { label: 'Unit tests', labelPhone: 'Tests', value: '~71', note: 'state machine to AI logic', notePhone: 'unit' },
    { label: 'Chaos test', labelPhone: 'Chaos', value: '1,000', note: 'messages, faults injected', notePhone: 'messages' },
    { label: 'Duplicates', labelPhone: 'Dupes', value: '30%', note: 'plus 30% out of order', notePhone: 'injected' },
    { label: 'Channels', value: '4', note: 'WhatsApp, SMS, email, RCS', notePhone: 'simulated' },
    { label: 'Seed data', labelPhone: 'Seed', value: '5k / 25k', note: 'customers / orders' },
    { label: 'Attribution', value: '72 h', note: 'last-touch window', notePhone: 'last touch' },
  ],
  preview: {
    slides: [
      {
        image: 'pulse-insights',
        alt: 'Pulse campaign insights for a demo campaign: delivery rate, messages rescued by failover, attributed revenue and delivery per channel',
        title: 'Insights.',
        caption: 'A demo campaign end to end: delivery, failover rescues and last-touch attribution, on seeded data.',
        captionPhone: 'A demo campaign end to end, on seeded data.',
      },
    ],
  },
  summary: {
    icon: 'sparkles',
    gradient: 'linear-gradient(145deg, #8E8BFF, #4B44C4)',
    text: 'Marketers describe an audience in plain English. The LLM only proposes a DSL that is validated and compiled, so it never writes SQL or sees PII.{{cite:pulse-architecture}} A 1,000-message test under injected chaos checks that delivery converges.{{cite:pulse-tests}}',
    textPhone: 'The LLM only proposes a validated DSL: it never writes SQL or sees PII.{{cite:pulse-architecture}} A 1,000-message test under injected chaos checks that delivery converges.{{cite:pulse-tests}}',
  },
  sections: [
    {
      kind: 'prose',
      id: 'problem',
      title: 'Problem',
      phone: 1,
      paragraphs: [
        'Marketers think in audiences: “customers who spent over ₹2,000 but haven’t ordered in 60 days”. Turning that into a query is a natural job for an LLM, and a risky one: a model that writes SQL is one prompt away from data it shouldn’t read, or change.',
        'Delivery is the other half. Callbacks arrive late, twice, out of order or not at all, and the CRM has to stay correct anyway: no double sends, no message stuck in the wrong state.',
      ],
      paragraphsPhone: [
        'Marketers think in audiences. An LLM can turn one into a query, but a model that writes SQL is one prompt away from data it shouldn’t touch. And delivery callbacks arrive late, twice or out of order.',
      ],
    },
    {
      kind: 'constraints',
      id: 'constraints',
      title: 'Constraints',
      phone: 'more',
      items: [
        { icon: 'lock', gradient: 'linear-gradient(145deg, #8E8BFF, #5149C9)', title: 'No SQL from the model.', text: 'The LLM proposes a DSL; only the compiler talks to the database.' },
        { icon: 'key-round', gradient: 'linear-gradient(145deg, #5AC8FA, #0A7CFF)', title: 'No PII to the model.', text: 'Customer data is encrypted with AES-256-GCM and found through a blind index.' },
        { icon: 'repeat', gradient: 'linear-gradient(145deg, #FFB340, #F08A00)', title: 'Messy callbacks.', text: 'Duplicates, reordering and failures are injected on purpose; the state must still converge.' },
        { icon: 'shield-check', gradient: 'linear-gradient(145deg, #4CD964, #1F8F3A)', title: 'Signed traffic.', text: 'HMAC-SHA256 on both directions of CRM ⇄ simulator traffic.' },
      ],
    },
    {
      kind: 'architecture',
      id: 'architecture',
      title: 'Architecture',
      titlePhone: 'How a campaign runs',
      phone: 2,
      intro: 'The model’s only output is a DSL, and the DSL is checked before anything runs. Delivery state lives in a forward-only state machine.',
      diagram: {
        width: 780,
        height: 456,
        nodes: [
          { x: 8, y: 24, icon: 'message-circle', bold: 'Marketer types', text: 'who to reach' },
          { x: 206, y: 24, icon: 'sparkles', bold: 'LLM proposes', text: 'a Segment DSL' },
          { x: 404, y: 24, icon: 'shield-check', bold: 'zod validates', text: 'whitelisted fields only' },
          { x: 602, y: 24, icon: 'database', tone: 'ok', bold: 'Compile', text: 'to a parameterised query' },
          { x: 404, y: 184, icon: 'ban', tone: 'warn', bold: 'Reject:', text: 'invalid DSL never runs' },
          { x: 602, y: 184, icon: 'send', bold: 'BullMQ', text: 'batches, retries, dead letters' },
          { x: 602, y: 344, icon: 'smartphone', bold: 'Channel simulator', text: 'WhatsApp, SMS, email, RCS' },
          { x: 404, y: 344, icon: 'key-round', bold: 'Signed callbacks,', text: 'HMAC both ways' },
          { x: 206, y: 344, icon: 'git-branch', tone: 'cite', bold: 'State machine,', text: 'forward-only, in SQL' },
          { x: 8, y: 344, icon: 'activity', bold: 'Attribution,', text: '72 h last touch' },
        ],
        edges: [
          { x: 158, y: 64, len: 46, dir: 'right', arrow: true },
          { x: 356, y: 64, len: 46, dir: 'right', arrow: true },
          { x: 554, y: 64, len: 46, dir: 'right', arrow: true },
          { x: 475, y: 112, len: 70, dir: 'down', arrow: true },
          { x: 673, y: 112, len: 70, dir: 'down', arrow: true },
          { x: 673, y: 272, len: 70, dir: 'down', arrow: true },
          { x: 556, y: 384, len: 46, dir: 'left', arrow: true },
          { x: 358, y: 384, len: 46, dir: 'left', arrow: true },
          { x: 160, y: 384, len: 46, dir: 'left', arrow: true },
        ],
        labels: [
          { x: 556, y: 40, w: 46, text: 'valid', tone: 'ok', align: 'center' },
          { x: 489, y: 140, w: 76, text: 'invalid', tone: 'warn', align: 'left' },
          {
            x: 8,
            y: 184,
            w: 360,
            size: 'note',
            text: 'The model’s output is data, not code: a DSL the compiler checks. It never writes SQL, touches the database or sees PII.',
          },
        ],
        text: 'Text version: a marketer describes an audience in plain English; the LLM proposes a Segment DSL, which zod validates against whitelisted fields and operators. Invalid DSL is rejected; valid DSL compiles to a parameterised Prisma query. BullMQ dispatches batches to a channel simulator (WhatsApp, SMS, email and RCS); HMAC-signed callbacks move each message through a forward-only state machine, and conversions are attributed last-touch within 72 hours.',
      },
      steps: [
        { text: '**Marketer types** who to reach, in plain English' },
        { text: '**LLM proposes** a Segment DSL' },
        { text: '**zod validates** it against whitelisted fields and operators' },
        { text: '**Invalid:** rejected; it never reaches the database', tone: 'warn', icon: 'ban' },
        { text: '**Valid:** compiled to a parameterised Prisma query', tone: 'ok', icon: 'circle-check' },
        { text: '**Sent:** BullMQ batches to the channel simulator; signed callbacks move a forward-only state machine', tone: 'cite', icon: 'send' },
      ],
    },
    {
      kind: 'decisions',
      id: 'decisions',
      title: 'Decisions',
      phone: 4,
      items: [
        {
          title: 'A validated DSL between the LLM and the database',
          chose: 'The LLM proposes a Segment DSL, validated with zod against whitelisted fields and operators; a separate compiler turns it into a parameterised Prisma query.',
          over: '[The alternative you weighed, e.g. letting the LLM write read-only SQL]',
          because: 'The model’s output becomes data the compiler can check, not code to trust. It never touches the database or sees PII.',
          cost: 'Marketers can ask only for what the whitelisted fields and operators can express.',
          becausePhone: 'The model’s output is data the compiler checks, not code to trust.',
          costPhone: 'Only what the whitelist can express.',
        },
        {
          title: 'A forward-only state machine, enforced in SQL',
          chose: 'Message statuses only move forward, enforced in the SQL WHERE clause of every update.',
          over: '[The option you weighed, e.g. checking transitions in application code]',
          because: 'Duplicate and out-of-order callbacks can’t move a message backwards.',
          cost: '[What it cost you]',
        },
        {
          title: 'Idempotent failover',
          chose: 'When a channel fails, the message fails over to the next one; a UNIQUE link to the parent message makes the failover idempotent.',
          over: '[The option you weighed]',
          because: 'A retried failover can’t send the same message twice.',
          cost: '[What it cost you]',
        },
      ],
    },
    {
      kind: 'ops',
      id: 'tests',
      title: 'Tests',
      phone: 3,
      ops: {
        cards: [
          { value: '~71', cite: 'pulse-tests', text: 'unit tests: state machine, HMAC, DSL compiler, crypto, receipts, failover, attribution, AI logic' },
          { value: '1,000', text: 'messages in an integration test under chaos, which asserts the system converges' },
          { value: '30%', text: 'duplicate callbacks injected, plus 30% out of order and 15% WhatsApp failures' },
        ],
        chainTitle: 'Every message',
        chain: [
          { label: 'BullMQ batch', icon: 'send' },
          { label: 'channel simulator' },
          { label: 'HMAC-signed callback' },
          { label: 'idempotent receipt' },
          { label: 'forward-only status' },
          { label: 'attributed, 72 h', icon: 'circle-check', tone: 'ok' },
        ],
        note: 'Failures retry with backoff and jitter, then land in a dead-letter queue; failover to the next channel is idempotent through a UNIQUE parent link.{{cite:pulse-delivery}}',
      },
    },
    {
      kind: 'list',
      id: 'limits',
      title: 'What broke, and the limits',
      toc: 'What broke',
      phone: 'more',
      tone: 'warn',
      items: [
        { text: 'Caught in review of AI-written code: a race between the SENT and delivered statuses, and how duplicates within one batch were merged.{{cite:pulse-ai-workflow}}' },
        { text: 'The channels are simulated, so the failure rates are injected, not measured on real providers.' },
        { text: 'The data is seeded (5,000 customers, 25,000 orders), not a real customer base.{{cite:pulse-brief}}' },
        { text: '[A real bug you hit: how you found it and what changed]', placeholder: true },
      ],
    },
    {
      kind: 'next',
      id: 'next',
      title: 'What I’d do next',
      toc: 'Next',
      phone: 'more',
      items: [
        { status: 'Planned', text: 'Make the README and ARCHITECTURE.md agree on the LLM provider chain.' },
        { status: 'Planned', text: '[What you’d build next on Pulse]' },
      ],
    },
    {
      kind: 'ai-note',
      id: 'ai-note',
      title: 'How I used AI tools',
      toc: 'AI-tool note',
      phone: 5,
      text: 'I built Pulse with Claude Code and kept a log of it, docs/AI_WORKFLOW.md: what I delegated, which decisions stayed mine, what I rejected, and what I caught in review, including a race between the SENT and delivered statuses and how in-batch duplicates were merged.{{cite:pulse-ai-workflow}}',
    },
  ],
  info: [
    { label: 'Role', value: '[Your role, e.g. solo build]', valuePhone: '[Your role]', phone: true },
    { label: 'Origin', value: 'Xeno Engineering Internship assignment, 2026 (SDE track)', valuePhone: 'Xeno internship assignment, 2026', phone: true },
    { label: 'Stack', value: 'NestJS · BullMQ · Prisma · zod', phone: true },
    { label: 'Services', value: '3 services · shared zod contracts' },
    { label: 'Security', value: 'HMAC-SHA256 both ways · AES-256-GCM for PII', valuePhone: 'HMAC-SHA256 · AES-256-GCM', phone: true },
    { label: 'Demo', value: 'pulse-ai-crm.vercel.app', href: 'https://pulse-ai-crm.vercel.app/' },
    { label: 'Repository', value: 'github.com/yash-vks-chauhan/Pulse', href: 'https://github.com/yash-vks-chauhan/Pulse' },
  ],
  sources: ['pulse-architecture', 'pulse-tests', 'pulse-delivery', 'pulse-ai-workflow', 'pulse-brief', 'pulse-demo'],
  more: ['gridee', 'ems-research'],
};
